name: bikers
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies: 
  flutter: 
   sdk: flutter 
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.1.0
  provider: ^6.0.5
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  firebase_storage_web: ^3.6.17
  firebase_auth: ^5.4.0
  flutter_spinkit: ^5.0.0
  intl: ^0.19.0

  # 로그인
  google_sign_in: ^6.2.2
  pinput: ^5.0.0
  country_code_picker: ^3.1.0

  # GPS
  geolocator: ^13.0.2

  # 사진
  pattern_formatter: ^4.0.0
  wechat_assets_picker: ^9.4.2
  wechat_camera_picker: ^4.1.2
  image_editor: ^1.0.1
  permission_handler: ^11.3.1

  # 이미지 사이즈를 압축해준다.
  flutter_image_compress: ^2.4.0
  # 임시 저장공간을 만들어 준다.(캐시 공간)
  path_provider: ^2.0.2
  # 이미지를 캐시해준다.
  cached_network_image: ^3.3.1
  # pull down시 리스트뷰를 refresh해준다.
  pull_to_refresh: ^2.0.0
  # 무한 스크롤뷰
  infinite_scroll_pagination: ^4.0.0
  # 이미지뷰 스크롤
  carousel_slider: ^5.0.0
  # GetX 상태관리 라이브러리
  get: ^4.6.6
  numberpicker: ^2.1.1
  # 웹뷰
  webview_flutter: ^4.10.0
  # http 통신
  http: ^1.2.2
  # 디바이스에서 다른 앱을 실행
  url_launcher: ^6.0.9
  flutter_datetime_picker_bdaya: ^3.0.2
  # 텍스트 필드에 마스크를 씌움
  mask_text_input_formatter: ^2.0.0
  # validator
  string_validator: ^1.1.0
  # 텍스트 접고 펼치기
  expandable_text: ^2.2.0
  # 다이얼로그 창에서 리스트 선택
  select_dialog: ^2.0.0
  # 디바이스에 맞춰 다이얼로그를 다르게 출력
  adaptive_dialog: ^2.0.0
  # 채팅을 위한 소켓 통신
  socket_io_client: ^3.0.2
  # 채팅 UI
  flutter_chat_ui: ^1.4.4
  # splash
  flutter_native_splash: ^2.4.4
  webview_flutter_android: ^4.2.0
    # 로그인 안드로이드
  google_sign_in_android: ^6.1.20
  
  sqflite: ^2.3.0
  
  video_player: ^2.8.1
  video_player_android: ^2.4.10  # 최신 버전으로 업데이트

  device_info_plus: ^11.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
cupertino_icons: ^1.0.2 

dev_dependencies:
  flutter_test:
   sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: 


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/naked.jpg
    - assets/dirt.jpg
    - assets/profileImage.jpg
    - assets/256.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts: 
   - family: PermanentMarker
     fonts: 
       - asset: assets/grafc.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
